### ISSUE TITLE
Errors in the training set

### ISSUE THREAD

**Issue by piotrpiekos** [google-deepmind/mathematics_dataset#11]
Hello

There is an error in generating arithmetic_add_or_sub examples.
Even in the pregenerated dataset in file arithmetic_add_or_sub.txt there are errors with this template. 
Examples:

```
What is the difference between -0.026764 and 0.1?
0.126764
```
```
What is the difference between 0.4 and 2.815?
2.415
```
It misses the minus sign for negative answers, for positive answers it looks fine 

```
What is the difference between 307 and 0.11?
306.89
```

**Comment by davidsaxton** [comment]
This is working as intended. In the dataset I've defined "difference between x and y" to be |x-y| rather than x - y, and as long as this convention is applied consistently throughout the dataset (which I think it is wherever the word "difference" is mentioned) then there shouldn't be any issues. (However please re-open this thread if you believe it's been applied inconsistently somewhere.)
